# 회원 생성
POST http://localhost:8080/signUp/customer
Content-Type: application/json

{
  "name": "주재영",
  "email": "jjy108@naver.com",
  "password": "1234",
  "birth": "1998-03-26",
  "phone": "010-1111-2222"
}

###
POST http://localhost:8080/signIn/customer
Content-Type: application/json

{
  "password": "1234",
  "email": "jjy108@naver.com"
}

###
POST http://localhost:8080/signUp/partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqankxMDhAbmF2ZXIuY29tIiwicm9sZXMiOlsiQ1VTVE9NRVIiXSwibmFtZSI6IuyjvOyerOyYgSIsImlhdCI6MTcwMzQzNjQ2MSwiZXhwIjoxNzAzNDQwMDYxfQ.kVXWxTAr9sxr19msuwxgyQGGgJqkwIr0XYFP7RZSb9TFYYjcDZ-wU6axrmYquPInCaJOgfe64e5UasgB-G5C1w

{
  "name": "주재영",
  "password": "1234",
  "email": "jjy108@naver.com"
}