### 로그인 (토큰발급)
POST http://localhost:8080/signIn/customer
Content-Type: application/json

{
  "password": "1234",
  "email": "jjy108@naver.com"
}

### 로그인 (토큰발급)
POST http://localhost:8080/signIn/customer
Content-Type: application/json

{
  "password": "2222",
  "email": "test2@naver.com"
}

### 매장 예약
POST http://localhost:8080/customer/reservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MkBuYXZlci5jb20iLCJyb2xlcyI6WyJDVVNUT01FUiJdLCJuYW1lIjoi7Jyg7KCAMiIsImlhdCI6MTcwNDY0NTI0OCwiaXNzIjoidGVzdDJAbmF2ZXIuY29tIiwiZXhwIjoxNzA0NjQ4ODQ4fQ.ntosFXqk7R-4f6G9JAegCvnQhhpINQu8oBvq23Mr6dczDttMdbxtyys4hybRQbZTDq6Rn-D6grh2bPxq35imkA

{
  "storeName": "매장2",
  "numOfPeople": 3,
  "reservationDate": "2024-01-04",
  "time": "7:30"
}

### 특정 매장 검색
GET http://localhost:8080/customer/search/store/매장2


### 로그인 토큰발급
POST http://localhost:8080/signIn/customer
Content-Type: application/json

{
  "password": "2222",
  "email": "test2@naver.com"
}

### 방문확인
POST http://localhost:8080/kiosk/confirmation/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BuYXZlci5jb20iLCJyb2xlcyI6WyJDVVNUT01FUiJdLCJuYW1lIjoi7Jyg7KCAMyIsImlhdCI6MTcwNDU1NjMxNSwiaXNzIjoidGVzdDNAbmF2ZXIuY29tIiwiZXhwIjoxNzA0NTU5OTE1fQ.CM8NQfR_jxs8Bc9PSfba1Db_eI1_FOMP7O_no0dhRxojHwCDApmxj_uHmfKPuJ2RHg-Hp6C4zwkDn2XS6BrcYQ

### 리뷰작성
POST http://localhost:8080/customer/review/25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BuYXZlci5jb20iLCJyb2xlcyI6WyJDVVNUT01FUiJdLCJuYW1lIjoi7Jyg7KCAMyIsImlhdCI6MTcwNDU1NjMxNSwiaXNzIjoidGVzdDNAbmF2ZXIuY29tIiwiZXhwIjoxNzA0NTU5OTE1fQ.CM8NQfR_jxs8Bc9PSfba1Db_eI1_FOMP7O_no0dhRxojHwCDApmxj_uHmfKPuJ2RHg-Hp6C4zwkDn2XS6BrcYQ

{
  "title": "유저2의 리뷰2",
  "contents": "유저2가 작성한 리뷰2입니다."
}

### 리뷰 삭제
DELETE http://localhost:8080/customer/review/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BuYXZlci5jb20iLCJyb2xlcyI6WyJDVVNUT01FUiJdLCJuYW1lIjoi7Jyg7KCAMyIsImlhdCI6MTcwNDU1NjMxNSwiaXNzIjoidGVzdDNAbmF2ZXIuY29tIiwiZXhwIjoxNzA0NTU5OTE1fQ.CM8NQfR_jxs8Bc9PSfba1Db_eI1_FOMP7O_no0dhRxojHwCDApmxj_uHmfKPuJ2RHg-Hp6C4zwkDn2XS6BrcYQ

### 리뷰수정
PUT http://localhost:8080/customer/review/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0M0BuYXZlci5jb20iLCJyb2xlcyI6WyJDVVNUT01FUiJdLCJuYW1lIjoi7Jyg7KCAMyIsImlhdCI6MTcwNDU1NjMxNSwiaXNzIjoidGVzdDNAbmF2ZXIuY29tIiwiZXhwIjoxNzA0NTU5OTE1fQ.CM8NQfR_jxs8Bc9PSfba1Db_eI1_FOMP7O_no0dhRxojHwCDApmxj_uHmfKPuJ2RHg-Hp6C4zwkDn2XS6BrcYQ

{
  "title": "수정된 제목1",
  "contents": "수정된 리뷰글입니다."
}